/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 assci.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/assci.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Curve.geometry} material={materials['Beu Metal']} position={[-0.092, 1.277, 0.013]} rotation={[-0.924, -0.503, -2.191]} scale={0.844} />
    </group>
  )
}

useGLTF.preload('/assci.glb')
